TabLayout: Add app theme. This class needs to be of style Theme.AppCompat, otherwise the app will FC. This has been left out in the previous commit: https://github.com/AOSPA/android_packages_apps_ParanoidPapers/commit/118230c8d50a21137381e3897247e77ae534aaec
This is what I have found in my logcat:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paranoid.ParanoidPapers/com.paranoid.ParanoidPapers.WallpaperActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.support.design.widget.TabLayout
java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

Change-Id: I7f81be55c04833a3a48155c121798d707d6aa10b
Signed-off-by: spezi77 <spezi7713@gmx.net>